# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Trimble.Connect
PackageVersion: 1.25.3.660
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S /v"/qn /norestart"
  SilentWithProgress: /exebasicui
UpgradeBehavior: install
ReleaseDate: 2025-06-23
Installers:
- Architecture: x64
  InstallerUrl: https://dist.download.tekla.com/software_download/TrimbleConnectSetup-1.25.3.660-x64.exe?Expires=1755825248&Signature=ixuNCI8VeHG~Qr1XLiBzG9Rp4F7eyyfLUxIWKvuQ2lp7tUs8Avk-pFgthY-dbPRjgAy1GAo6qRDXhHu8ZeyPwvayEr5s~mOXLi-1RTzFaGQ0NSkqKDqiVSswjYlJDHN-QAcu~O80rOLeJHXQQAzQelIds4kmTSPeHmUROivfPr3NfudZ8U82e1M9wXDgc5AUsCEMp0UnDLNzVS547d8vPtliyyNNggk0nrbY4gvcNMy9A4mbXzwr0YexIInyL4yWTizVRebL4f~uVsGHFQvSow3MYIgXmWnGlIyC6LkvMcuvE3akK2YCUyVlw1HDNrN0AtpGoRHORGvVe0nl~rezIw__&Key-Pair-Id=APKAJCEODGU67GHOWXPA
  InstallerSha256: 65591F39DB199EA5829F21BF85D13198FBD662B1CDC117730A611BDCD30701BF
ManifestType: installer
ManifestVersion: 1.10.0
