# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Newtonsoft.Json
PackageVersion: 13.0.3
InstallerType: zip
InstallModes:
- silent
UpgradeBehavior: install
ReleaseDate: 2023-03-08
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/JamesNK/Newtonsoft.Json/releases/download/13.0.3/Json130r3.zip
  InstallerSha256: 093C8BC046C435758C975EA6FE5D5C333EB23850859EB0D949E5F23AC26B6286
ManifestType: installer
ManifestVersion: 1.10.0
