# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Jibble.Jibble
PackageVersion: 46.1.5
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: '{5522A08F-7F42-30AC-AEC9-00C528B871F9}'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- DisplayName: Jibble - Time Tracking
  Publisher: Jibble
  ProductCode: '{5522A08F-7F42-30AC-AEC9-00C528B871F9}'
  UpgradeCode: '{9AB7FD68-31FE-4671-B21A-8AD92D73FC8E}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Jibble - Time Tracking'
Installers:
- Architecture: x64
  InstallerUrl: https://files.jibble.io/desktop/windows/prod/jibble.msi
  InstallerSha256: 15E2C58AC441E4AE28ED803BFB021A923254042DF559C492AB615ED3A3A122BD
ManifestType: installer
ManifestVersion: 1.12.0
