# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FrSky.EthosSuite
PackageVersion: 1.6.3
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: 234726f7-d84e-569e-899e-e9f080f161a7
ReleaseDate: 2025-05-15
AppsAndFeaturesEntries:
- DisplayName: Ethos Suite 1.6.3
  Publisher: FrSky RC
  ProductCode: 234726f7-d84e-569e-899e-e9f080f161a7
Installers:
- Architecture: x64
  InstallerUrl: https://www.frsky-rc.com/wp-content/uploads/Downloads/Firmware/EthosSuite/Ethos-Suite-Windows-1.6.3.exe
  InstallerSha256: CD68F86C7C939E4C87FD78FFAC8352B46AB16767C8BF4A4306FDF1C8D3FABA8E
ManifestType: installer
ManifestVersion: 1.12.0
