# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: FrSky.EthosSuite
PackageVersion: 1.6.3
PackageLocale: en-US
Publisher: FrSky Electronic Co., Ltd.
PublisherUrl: https://www.frsky-rc.com/
PublisherSupportUrl: https://www.frsky-rc.com/contact/
Author: FrSky Electronic Co., Ltd.
PackageName: Ethos Suite
PackageUrl: https://ethos.frsky-rc.com/
License: Proprietary
LicenseUrl: https://www.frsky-rc.com/frsky-website-terms-of-use/
Copyright: Copyright © FrSky Electronic Co., Ltd. All rights reserved.
ShortDescription: Ethos Suite is a PC application for managing and updating FrSky radios, receivers, firmware, accessories, models, images, audio files, and other ETHOS components.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
