# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Zoho.WorkDriveTrueSync
PackageVersion: 5.16.0
InstallerLocale: en-US
InstallerType: msi
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: '{F8BF7828-8BE0-4A12-975C-34A5813EF86B}'
AppsAndFeaturesEntries:
- DisplayName: Zoho WorkDrive TrueSync 5.16.0
  ProductCode: '{F8BF7828-8BE0-4A12-975C-34A5813EF86B}'
  UpgradeCode: '{C869DD4C-D7EA-4B72-8A02-C1D3454801D5}'
Installers:
- Architecture: x64
  InstallerUrl: https://files-accl.zohopublic.com/public/tswin/download/d501492ef336331284839784096b057b
  InstallerSha256: 206EA9FA2B5D1FF5CDBF029231714E56B246943C2938D4939DF88D47C3C6FD61
ManifestType: installer
ManifestVersion: 1.12.0
